### ISSUE TITLE
Add `<meta>` tag for `https://*.webxrexperiments.com` Origin-Trial token

### ISSUE THREAD

**Issue by cvan** [arturitu/xr-store#1]
Without needing a user to enable the flags for Cardboard or Daydream modes, I would recommend enrolling in the WebVR Origin Trial for Chrome for Android.

Sign up here: https://docs.google.com/forms/d/1OTvEk-VfavyKkMxef0Tvs0RFycl9NNu1vdg3FrqJhX8/viewform?edit_requested=true

**Comment by blairmacintyre** [comment]
done.
