### ISSUE TITLE
Force redirect to HTTPS

### ISSUE THREAD

**Issue by cvan** [arturitu/xr-store#2]
I would recommend handling the HTTPS redirect at the server level (Cloudflare/CloudFront).

As a workaround until that's in place, you can use this JavaScript in your `index.html`:

```js
if (!window.location.port && window.location.protocol === 'http:') {
  window.location.href = 'https:' + window.location.href.substring(6);
}
```

🔒:smile:

**Comment by blairmacintyre** [comment]
Are you talking for xr-store.webxrexperiments.com?  I can do a force-https there.  

Please don't add the javascript;  I've done this in the past, but it's a pain in the butt when you need to do local non-https testing.  Normally, I'm using ngrok and thus get https, but sometimes not.

**Comment by blairmacintyre** [comment]
Ok, I turned on force https on the site, along with some other webxrexperiements. com sites.
